openapi: 3.0.0
info:
  version: '1.0'
  title: ''
  description: ''
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/james-d/Aiport-API/1.0
  - url: 'http://localhost:3000'
paths:
  /airports:
    get:
      summary: returns an array of airports
      tags:
        - Airports
      responses:
        '200':
          description: returns an array of airports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
    post:
      summary: adds an airport.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                airport_icao:
                  type: string
                airport_iata:
                  type: string
                airport_name: 
                  type: string
                airport_city:
                  type: string
                airport_state:
                  type: string
                airport_country:
                  type: string
                airport_elevation:
                  type: number
                airport_latitude:
                  type: number
                airport_longitude:
                  type: number
            
      tags:
        - Airports
      responses:
        '200':
          description: returns a success status code.
        
  /airports/{id}:
    get:
      summary: returns an airport with the given ID.
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: string
      tags:
        - Airports
      responses:
        '200':
          description: returns the given airport
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Airport'
    delete:
      summary: deletes an airport with the given ID.
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: returns a success code.
    put:
      summary: Replaces an airport with the given ID.
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                airport_icao:
                  type: string
                airport_iata:
                  type: string
                airport_name: 
                  type: string
                airport_city:
                  type: string
                airport_state:
                  type: string
                airport_country:
                  type: string
                airport_elevation:
                  type: number
                airport_latitude:
                  type: number
                airport_longitude:
                  type: number
      tags:
        - Airports
      responses:
        '200':
          description: returns the replaced airport
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
                  
    patch:
      summary: Updates an airport with the given ID.
      parameters: 
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                airport_icao:
                  type: string
                airport_iata:
                  type: string
                airport_name: 
                  type: string
                airport_city:
                  type: string
                airport_state:
                  type: string
                airport_country:
                  type: string
                airport_elevation:
                  type: number
                airport_latitude:
                  type: number
                airport_longitude:
                  type: number
      tags:
        - Airports
      responses:
        '200':
          description: returns the replaced airport
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Airport'
                  
                  
components:
  schemas:
    Airport:
      type: object
      properties:
        icao:
          type: string
        iata:
          type: string
        name:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        elevation:
          type: integer
        lat:
          type: number
        lon:
          type: number
        tz:
          type: string
      example:
        icao: 00AK
        iata: ''
        name: Lowell Field
        city: Anchor Point
        state: Alaska
        country: US
        elevation: 450
        lat: 59.94919968
        lon: -151.695999146
        tz: America/Anchorage
    Plane:
      type: object
      properties:
        origin:
          type: string
        destination:
          type: string
        flight_number:
          type: string
        
      example:
        origin: "London"
        destination: "Dubai"
        flight_number: "04OKFS4"
tags:
  - name: Airports
    description: Airport management